### ISSUE TITLE
Issue installing mysql

### ISSUE THREAD

**Issue by timbroder** [ei-grad/ansible-newrelic-npi#3]
Hello,

I'm trying to install mysql using:

```
  tasks:
    - name: newrelic db
      npi: name=com.newrelic.plugins.mysql.instance state=present config='{"agents":[{"name":"My Ansible-managed database","host":"localhost","metrics":"status,newrelic","user":"newrelic","passwd":"XrvHewksxu2jQ49Xr87WAyk8hNzCx7hkXoVgomUw6m3g7xZzva"}]}'
```

I'm getting this error:

```
TASK [newrelic db] *************************************************************
task path: /Users/timbroder/workspace/kidfund/automation/ansible/db.playbook:8
<###> ESTABLISH CONNECTION FOR USER: dbadmin on PORT 22 TO ###
<###> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1472857926.08-86656108752026 `" && echo ansible-tmp-1472857926.08-86656108752026="` echo $HOME/.ansible/tmp/ansible-tmp-1472857926.08-86656108752026 `" ) && sleep 0'
<###> PUT /var/folders/wq/jy6g66fn3p14s4x953y4ncbh0000gn/T/tmpXCe2l4 TO /home/dbadmin/.ansible/tmp/ansible-tmp-1472857926.08-86656108752026/npi
<###> PUT /var/folders/wq/jy6g66fn3p14s4x953y4ncbh0000gn/T/tmpfVkG_o TO /home/dbadmin/.ansible/tmp/ansible-tmp-1472857926.08-86656108752026/args
<###> EXEC /bin/sh -c 'sudo -H -S  -p "[sudo via ansible, key=extlbgjjequoqeeijjmtnnscgwjqkopt] password: " -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-extlbgjjequoqeeijjmtnnscgwjqkopt; LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /bin/bash /home/dbadmin/.ansible/tmp/ansible-tmp-1472857926.08-86656108752026/npi /home/dbadmin/.ansible/tmp/ansible-tmp-1472857926.08-86656108752026/args; rm -rf "/home/dbadmin/.ansible/tmp/ansible-tmp-1472857926.08-86656108752026/" > /dev/null 2>&1'"'"' && sleep 0'
fatal: [DBHOST]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "npi"}, "module_stderr": "", "module_stdout": "/home/dbadmin/.ansible/tmp/ansible-tmp-1472857926.08-86656108752026/args: line 1: Ansible-managed: command not found\r\n", "msg": "MODULE FAILURE", "parsed": false}
```

Any ideas?

Thanks!

**Comment by ei-grad** [comment]
Which ansible version do you use?

Btw, current master was broken (as of README point at least). I have fixed it, you can try to update. But it doesn't look like your issue is related to this, its error is different...

**Comment by ei-grad** [comment]
Oh. I got it!

It can't find npi binary, which is installed by this role.

You have to run `ansible-newrelic-npi` as a role first, then you could use npi module.

**Comment by timbroder** [comment]
hmm, I think I am, at least I'm running: `ei-grad.newrelic-npi`

This is the full playbook:

```
- hosts: databases
  vars_files:
    - vars/mysql.yml
    - vars/newrelic.yml
  become: true
  become_user: root
  tasks:
    - hostname: name="{{ host_hostname }}"
  roles:
    - role: geerlingguy.mysql
    - role: ei-grad.newrelic-npi
  post_tasks:
    - name: newrelic db
      npi: name=com.newrelic.plugins.mysql.instance state=present config='{"agents":[{"name":"My Ansible-managed database","host":"localhost","metrics":"status,newrelic","user":"newrelic","passwd":"XrvHewksxu2jQ49Xr87WAyk8hNzCx7hkXoVgomUw6m3g7xZzva"}]}'
```

I installed via [galaxy](https://galaxy.ansible.com/ei-grad/newrelic-npi/) and I'm running `ansible 2.1.0.0`
