### ISSUE TITLE
Plugin`config/plugin.json` replaces double-quotes with single-quotes

### ISSUE THREAD

**Issue by pkaeding** [ei-grad/ansible-newrelic-npi#4]
I'm trying to specify a JSON config for a plugin, but the JSON is being mangled. Specifically, the double-quotes are being converted to single-quotes.

I have the following task:

```
- name: Install ES New Relic plugin
  npi: 
    name: me.snov.newrelic-elasticsearch 
    state: present 
    config: >
      {"agents":[{"host": "{{ ansible_default_ipv4.address }}", "port": 9200}]}
```

When I run it, it results in a `/opt/newrelic-npi/plugins/me.snov.newrelic-elasticsearch/newrelic-elasticsearch-plugin-2.3.0/config/plugin.json` file like this:

```
{'agents': [{'host': '10.10.4.51', 'port': 9200}]}
```

When I define the task in the one0line format, I get the same result:

```
- name: Install ES New Relic plugin
  npi: name=me.snov.newrelic-elasticsearch state=present config='{"agents":[{"host":"{{ ansible_default_ipv4.address }}","port":9200}]}'
```

How can I inject this config for the plugin?

I am using Ansible version 2.3.0.0.
